services:
  - type: web
    name: tech-stocker
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        sync: false
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        fromDatabase:
          name: tech-stocker-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: tech-stocker-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: tech-stocker-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: tech-stocker-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: tech-stocker-db
          property: password
    healthCheckPath: /
    autoDeploy: true

databases:
  - name: tech-stocker-db
    databaseName: tech_stocker
    user: tech_stocker
    plan: free 